export const TAB_BAR_CLEARANCE = 56
export const FAB_SAFE_BOTTOM_MIN = 10
export const PAGE_HONEYCOMB_CORNER_BLEED = 40
export const APP_HEADER_TO_BODY_GAP = 12
export const LAB_STACK_HEADER_TO_BODY_GAP = 6
export const PAGE_HORIZONTAL_GUTTER = 20

export const SHOP_GRID_HORIZONTAL_PADDING = PAGE_HORIZONTAL_GUTTER
export const SHOP_GRID_GAP = 12
export const FEATURED_COLLECTION_HORIZONTAL_PADDING = PAGE_HORIZONTAL_GUTTER
export const FEATURED_COLLECTION_CARD_GAP = 12
export const LAB_QUICK_VERIFY_QR_BOX = 168
export const LAB_FLAVOR_RADAR_CENTER_X = 100
export const LAB_FLAVOR_RADAR_CENTER_Y = 95
