import type { Product } from "@/models/product";

/** Demo storefront rows until a public catalog API exists. */
export const STOREFRONT_PRODUCTS: Product[] = [
  {
    id: "prod_wild_highland",
    lang: "en",
    slug: "wild-highland-honey",
    name: "Wild Highland Honey",
    description:
      "Single-origin raw honey from the Adamaoua highlands. Floral, balanced, and lab-checked for purity before it reaches your table.",
    price: 24,
    category_id: "pcat_honey",
    sub_category_id: "psc_gold_highlands",
    category_code: "HONEY",
    stock_quantity: 40,
    origin_region: "Adamaoua Region",
    featured_image: "/images/premium_photo-1664273586606-d7c9804729c2.jpg",
    measurement_type: "MASS",
    measurement_unit: "GRAM",
    measurement_value: 500,
    net_grams: 500,
    net_milliliters: null,
    attributes: null,
    apparel_size: null,
  },
  {
    id: "prod_forest_white",
    lang: "en",
    slug: "forest-white-honey",
    name: "Forest White Honey",
    description:
      "Delicate Oku highland white honey with a creamy melt. Each jar reflects the forest canopy and careful cold extraction.",
    price: 18,
    category_id: "pcat_honey",
    sub_category_id: "psc_oku_white",
    category_code: "HONEY",
    stock_quantity: 30,
    origin_region: "Oku Highlands",
    featured_image: "/images/photo-1590334280707-9d5e0f60a539.jpg",
    measurement_type: "MASS",
    measurement_unit: "GRAM",
    measurement_value: 250,
    net_grams: 250,
    net_milliliters: null,
    attributes: null,
    apparel_size: null,
  },
  {
    id: "prod_beeswax_candles",
    lang: "en",
    slug: "raw-beeswax-candles",
    name: "Raw Beeswax Candles",
    description:
      "Hand-poured pair of candles using filtered beeswax from partner apiaries. Warm light, subtle honeyed aroma.",
    price: 32,
    category_id: "pcat_honey_derived",
    sub_category_id: "psc_beeswax",
    category_code: "HONEY_DERIVED",
    stock_quantity: 25,
    origin_region: "Southwest",
    featured_image: "/images/HoneyFrame_Scrapping-600x600.png",
    measurement_type: "COUNT",
    measurement_unit: "UNIT",
    measurement_value: 2,
    net_grams: null,
    net_milliliters: null,
    attributes: null,
    apparel_size: null,
  },
  {
    id: "prod_ventilated_suit",
    lang: "en",
    slug: "ventilated-bee-suit",
    name: "Ventilated Beekeeping Suit",
    description:
      "Triple-layer mesh suit for hot-climate work. Reinforced zips, detachable veil, and pockets sized for hive tools.",
    price: 189,
    category_id: "pcat_beekeeping_supply",
    sub_category_id: "psc_protective_harvesting",
    category_code: "BEEKEEPING_SUPPLY",
    stock_quantity: 12,
    origin_region: "Partner workshop",
    featured_image: "/images/photo-1549269459-ba9e31874ef2.jpg",
    measurement_type: "COUNT",
    measurement_unit: "UNIT",
    measurement_value: 1,
    net_grams: null,
    net_milliliters: null,
    attributes: null,
    apparel_size: "L",
  },
  {
    id: "prod_ph_kit",
    lang: "en",
    slug: "honey-ph-test-kit",
    name: "Honey pH Screening Kit",
    description:
      "Field kit with calibrated strips and vials for quick acidity checks—ideal for batch documentation alongside lab sends.",
    price: 45,
    category_id: "pcat_other",
    sub_category_id: "psc_general_other",
    category_code: "OTHER",
    stock_quantity: 60,
    origin_region: "Lab partners",
    featured_image: "/images/Untitled-design-5-600x600.png",
    measurement_type: "MASS",
    measurement_unit: "GRAM",
    measurement_value: 120,
    net_grams: 120,
    net_milliliters: null,
    attributes: null,
    apparel_size: null,
  },
];

export function getStorefrontProductBySlug(slug: string): Product | undefined {
  return STOREFRONT_PRODUCTS.find((product) => product.slug === slug);
}
