import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";

import { PublicFooter } from "@/components/public/layout/public-footer";
import { PublicHeader } from "@/components/public/layout/public-header";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Suspense>
          <RefineContext>
            <div className="min-h-dvh flex flex-col bg-[var(--surface)] text-[var(--foreground)]">
              <PublicHeader />
              {children}
              <PublicFooter />
            </div>
          </RefineContext>
        </Suspense>
      </body>
    </html>
  );
}
